---
title: '异常机制'
date: 2021-11-06 14:48:15
# 永久链接
permalink: '/java/exception'
sidebar: 'auto'
isShowComment: true
categories:
 - java
tags:
 - Exception
---





## 什么是异常

>   实际工作中，遇到的情况不可能是非常完美的。比如：你写的某个模块，用户输入的不一定符合你的额要求、你的程序要打开某个文件，这个文件可能不存在或者文件格式不对，你要读取的数据库的数据，可能是空的等等。程序跑着跑着内存或硬盘可能满了。



>   软件程序在运行过程中，非常可能遇到刚出现的异常问题，我们统称为异常，英文是`Exception`，我们需要让我们写出的程序做出合理的处理，而不至于程序崩溃。



异常的概念解析：

-   异常指程序运行中出现的不期而至的各种状况
-   异常发生在程序运行期间，它影响了正常的程序执行流程



案例

`Exception in thread "main" java.lang.StackOverflowError`

```java
public class Demo01 {
    public static void main(String[] args) {
        new Demo01().a(); // 无限循环，程序肯定会出错
    }

    public void a() {
        b();
    }

    private void b() {
        a();
    }
}

```



## 简单分类

-   检查型异常：检查型异常就是用户错误或问题引起的异常，这是程序员无法预见的。这些异常在编译时不能被简单地忽略。
-   运行时异常：运行时异常是可能被程序员避免的异常。与检查型异常相反，运行时异常可以在编译时被忽略。
-   错误：错误不是异常，而是脱离程序员控制的问题。错误在代码中通常被忽略。它们一般在编译也是检查不到的。



## 异常体系结构

Java把异常当做对象来处理，并定义了一个基类`java.lang.Throwable`作为所有异常的超类

在Java API中已经定义了许多异常类，这些异常类分为两大类，错误`Error`和异常`Exception`



### Error

-   Error类对象由Java虚拟机生成并抛出，大多数错误与代码编写者所执行的操作无关。

-   Java虚拟机运行错误(Virtual MachineError)，当JVM不再有继续执行操作所需的内存资源时，将出现`OutOfMemoryError`。这些异常发生时，Java虚拟机(JVM)一般会选择线程终止
-   发生在虚拟机试图执行应用时，如类定义错误`NoClassDefFoundError`、链接错误(`LinkageError`)。这些错误是不可查的，因为他们在应用程序的控制和处理能力之外，而且绝大多数是程序运行时不允许出现的状况。



### Exception

在Exception分支中有一个重要的子类`RuntimeException`（运行时异常）

-   `ArrayIndexOutOfBoundsException`（数组下标越界）
-   `NullPointerException`（空指针异常）
-   `ArithmeticException`（算术异常）
-   `MissingResourceException`（丢失资源）
-   `ClassNotFoundException`（找不到类）等异常

>   这些异常是不检查异常，程序中可以选择捕获处理，也可以不处理。这些异常一般是由程序逻辑错误引起的，程序应该从逻辑角度尽可能避免这类异常的发生。



:::tip

Error和Exception的区别：Error通常是灾难性的致命的错误，是程序无法控制和处理的。当出现这个异常时，Java虚拟机一般会选择终止线程；Exception通常情况下是可以被程序处理的，并且在程序中应该尽可能的去处理这些异常。

:::



## 异常处理机制

-   抛出异常
-   捕获异常



**异常处理五个关键字：try、catch、finally、throw、throws**

---



案例1：

```java
public class Demo01 {
    public static void main(String[] args) {
        int a = 1;
        int b = 0;
        try {
            // 监控区域
            System.out.println(a / b);
        } catch (ArithmeticException e) { // 想要捕捉的异常类型 可以写多个catch，最大的异常往下面写
            e.printStackTrace();
            System.out.println("程序出现异常，变量b不能为0");
        } finally {
            // 善后工作，最后都会执行
            System.out.println("finally");
        }
    }
}

```

```bash
java.lang.ArithmeticException: / by zero
	at com.exceptions.Demo01.main(Demo01.java:9)
程序出现异常，变量b不能为0
finally
```

:::tip

`finally`可以不要，但是后续IO流，需要做资源关闭 ，需要添加；



**假设要捕获多个异常，catch的异常要从小范围到大范围的写，最大的写在最下面**

:::

---

案例：

```java
public static void main(String[] args) {
    int a = 1;
    int b = 0;

    try {
        if (b == 0) {
            // 主动抛出异常
            throw new ArithmeticException("被除数不能为0");
        }
        System.out.println(a / b);
    } catch (Exception e) {
        //            e.printStackTrace(); // 打印栈错误信息
        System.out.println("exception");
    }
}
```

---

**假设这个方法中处理不了异常，方法上抛出异常**

```java
package com.exceptions;

public class Demo01 {
    public static void main(String[] args) {
        int a = 1;
        int b = 0;

        try {
            new Demo01().divide(a, b);
        } catch (ArithmeticException e) {
            e.printStackTrace();
        }
    }

    public void divide(int a, int b) throws ArithmeticException {
        if (b == 0) {
            throw new ArithmeticException("被除数不能为0");
        }
        System.out.println(a / b);
    }
}

```



## 自定义异常

>   用户自定义异常类，只需要继承`Exception`类即可



在程序中使用自定义异常类，大体可分为以下步骤：

-   创建自定义异常类
-   在方法中通过`throw`关键字抛出异常对象
-   如果在当前破案出异常的方法中处理异常，可以使用`try-catch`语句捕获并处理；否则在方法的声明处通过`throws`关键字指明要抛出给方法调用者的异常，继续进行下一步操作。
-   在出现异常方法的调用者中捕获并处理异常。



```java
package com.exceptions;

public class MyException extends Exception {

    // 传递数字>10
    private int detail;

    public MyException(int a) {
        this.detail = a;
    }

    @Override
    public String toString() {
        return "MyException{" + "detail=" + detail + "}";
    }
}

```

```java
package com.exceptions;

public class Test {

    // 可能会存在异常的方法
    static void test(int a) throws MyException {
        System.out.println("传递的参数为: " + a);

        if (a > 10) {
            throw new MyException(a);
        }

        System.out.println("ok");
    }

    public static void main(String[] args) {
        try {
            test(11);
        } catch (MyException e) {
//            e.printStackTrace();
            // 增加一些处理异常的代码
            System.out.println("MyException: " + e);
        }
    }
}

```

```bash
传递的参数为: 11
MyException: MyException{detail=11}
```



## 总结

-   处理运行时异常时，采用逻辑去合理规避同时辅助`try-catch`处理
-   在多重`catch`块后面，可以加`catch (Exception e)`来处理可能会被遗漏的异常
-   对于不确定的代码，也可以加上`try-catch`，处理潜在的异常
-   尽量去处理异常，切忌只是简单地调用`printStackTrack()`去打印输出
-   具体如何处理异常，要根据不同的业务需要和异常类型去决定
-   尽量添加`finally`语句块去释放占用的资源

